// biome-ignore assist/source/organizeImports: <AUTO-GENERATED>
import { useId, type FC } from "react";
import { registerLocale } from "react-datepicker"; // 追加
import { ja } from "date-fns/locale/ja"; // 追加
import "react-datepicker/dist/react-datepicker.css"; // 必要ならスタイルも
import type { FurusatoRecord, History } from "@/types/tax";

// コンポーネントの外で1回だけ実行されるように配置
registerLocale("ja", ja);

interface FurusatoFormProps {
  onSubmit: (e: React.FormEvent) => void;
  formData: Omit<FurusatoRecord, "id">;
  setFormData: (data: any) => void;
  history: History;
  editingId: string | null;
  onCancelEdit: () => void;
}

export const FurusatoForm: FC<FurusatoFormProps> = ({
  onSubmit,
  formData,
  setFormData,
  history,
}) => {
  // すべての入力項目とリスト用に一意のIDを生成
  const dateId = useId();
  const cityId = useId();
  const cityListId = useId();
  const amountId = useId();
  const memoId = useId();
  const isOneStopId = useId();
  const isReceivedId = useId();

  return (
    <form
      onSubmit={onSubmit}
      className="bg-white dark:bg-slate-800 p-8 rounded-3xl shadow-xl border border-slate-100 dark:border-slate-700 mb-12 animate-in fade-in slide-in-from-top-4 duration-500"
    >
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {/* 日付 */}
        <div className="space-y-2">
          <label
            htmlFor={dateId}
            className="text-xs font-black text-slate-500 dark:text-slate-400 ml-1 tracking-widest uppercase"
          >
            受診日
          </label>
          <input
            type={dateId}
            required
            value={formData.date}
            onChange={(e) => setFormData({ ...formData, date: e.target.value })}
            className="w-full p-4 rounded-2xl bg-slate-50 dark:bg-slate-900 border-2 border-transparent focus:border-blue-500 focus:bg-white dark:focus:bg-slate-800 outline-none transition-all font-bold text-slate-700 dark:text-slate-200"
          />
        </div>

        {/* 自治体名の入力 */}
        <div className="space-y-2">
          <label
            htmlFor={cityId}
            className="text-xs font-black text-slate-500 dark:text-slate-400 ml-1 tracking-widest uppercase"
          >
            寄付先の自治体
          </label>
          <input
            type="text"
            required
            list={cityListId}
            placeholder="受診した人の名前"
            value={formData.city}
            onChange={(e) => setFormData({ ...formData, city: e.target.value })}
            className="w-full p-4 rounded-2xl bg-slate-50 dark:bg-slate-900 border-2 border-transparent focus:border-blue-500 focus:bg-white dark:focus:bg-slate-800 outline-none transition-all font-bold text-slate-700 dark:text-slate-200"
          />
          <datalist id={cityListId}>
            {history.cities.map((city) => (
              <option key={city} value={city} />
            ))}
          </datalist>
        </div>

        {/* 寄付金額 */}
        <div className="space-y-2">
          <label
            htmlFor={amountId}
            className="text-xs font-black text-slate-500 dark:text-slate-400 ml-1 tracking-widest uppercase"
          >
            寄付金額
          </label>
          <div className="relative">
            <span className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400 font-bold">
              ¥
            </span>
            <input
              id={amountId}
              type="number"
              required
              min="0"
              value={formData.amount || ""}
              onChange={(e) => setFormData({ ...formData, amount: Number(e.target.value) })}
              className="w-full p-4 pl-10 rounded-2xl bg-slate-50 dark:bg-slate-900 border-2 border-transparent focus:border-blue-500 focus:bg-white dark:focus:bg-slate-800 outline-none transition-all font-bold text-slate-700 dark:text-slate-200"
            />
          </div>
        </div>

        {/* 返礼品のメモ */}
        <div className="space-y-2">
          <label
            htmlFor={memoId}
            className="text-xs font-black text-slate-500 dark:text-slate-400 ml-1 tracking-widest uppercase"
          >
            メモ（任意）
          </label>
          <input
            id={memoId}
            type="text"
            required
            // list={providerListId}
            placeholder="お米２０Kgなど"
            value={formData.memo}
            onChange={(e) => setFormData({ ...formData, memo: e.target.value })}
            className="w-full p-4 rounded-2xl bg-slate-50 dark:bg-slate-900 border-2 border-transparent focus:border-blue-500 focus:bg-white dark:focus:bg-slate-800 outline-none transition-all font-bold text-slate-700 dark:text-slate-200"
          />
        </div>
      </div>

      {/* 特例申請（ワンストップ申請）チェックボックス */}
      <div className="mt-6 flex items-center gap-4">
        <input
          id={isOneStopId}
          type="checkbox"
          checked={formData.isOneStop}
          onChange={(e) => setFormData({ ...formData, isOneStop: e.target.checked })}
          className="w-5 h-5 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
        />
        <label
          htmlFor={isOneStopId}
          className="text-sm font-medium text-slate-700 dark:text-slate-300"
        >
          特例申請
        </label>
      </div>
    </form>
  );
};
